#!/bin/bash

set -Eeo pipefail

for command in "$@"
do
  echo "--- ${command} ---"
  case "${command}" in
    _build)
        rm -rf build/
        gradle assemble
        ;;
    build)
        ./tasks _build
        ;;
    _test_unit)
        gradle test
        ;;
    test_unit)
        ./tasks _test_unit
        ;;
    _dep)
        gradle dependencyCheckAnalyze
        ;;
    dep)
        ./tasks _dep
        ;;
    _test_coverage)
        gradle jacocoTestCoverageVerification
        ;;
    test_coverage)
        ./tasks _test_coverage
        ;;
    _code_quality)
        gradle check -x test
        ;;
    code_quality)
        ./tasks _code_quality
        ;;
    run_local)
        ./gradlew build
        ./gradlew bootRun
        ;;
    _validate)
        ./tasks _test_unit _test_coverage _code_quality
        ;;
    validate)
        ./tasks _validate
        ;;
  esac
done

set +e